#include "Common.h"
#include "Configuration/SettingsManager.h"
#include "Core/CorrectionEngine.h"
#include "System/GlobalHotkeyManager.h"
#include "System/OverlayManager.h"
#include "UI/OverlayWindow.h"
#define HOTKEY_OPEN 1
static SettingsManager* gSettings=nullptr; static GlobalHotkeyManager gHotkeys; static OverlayManager gOverlay; static NOTIFYICONDATAW gNid{};
static LRESULT CALLBACK HiddenProc(HWND h,UINT m,WPARAM w,LPARAM l){ if(m==WM_HOTKEY&&w==HOTKEY_OPEN){ gOverlay.Toggle(); return 0;} if(m==WM_APP+2){ if(LOWORD(l)==WM_LBUTTONDBLCLK) gOverlay.Show(); if(LOWORD(l)==WM_RBUTTONUP){ HMENU menu=CreatePopupMenu(); AppendMenuW(menu,MF_STRING,1,L"Show korect"); AppendMenuW(menu,MF_STRING,2,L"Quit"); POINT p; GetCursorPos(&p); SetForegroundWindow(h); int cmd=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_RIGHTBUTTON,p.x,p.y,0,h,nullptr); DestroyMenu(menu); if(cmd==1) gOverlay.Show(); if(cmd==2) PostQuitMessage(0);} return 0;} if(m==WM_DESTROY){ Shell_NotifyIconW(NIM_DELETE,&gNid); PostQuitMessage(0); return 0;} return DefWindowProcW(h,m,w,l); }
static HWND CreateHidden(){ WNDCLASSW wc{}; wc.lpfnWndProc=HiddenProc; wc.hInstance=GetModuleHandleW(nullptr); wc.lpszClassName=L"KorectHiddenWindow"; RegisterClassW(&wc); return CreateWindowW(L"KorectHiddenWindow",L"korect hidden",0,0,0,0,0,HWND_MESSAGE,nullptr,wc.hInstance,nullptr); }
static void AddTray(HWND h){ gNid.cbSize=sizeof(gNid); gNid.hWnd=h; gNid.uID=100; gNid.uFlags=NIF_MESSAGE|NIF_TIP|NIF_ICON; gNid.uCallbackMessage=WM_APP+2; gNid.hIcon=LoadIconW(nullptr,IDI_APPLICATION); wcscpy_s(gNid.szTip,L"korect - Ctrl+Shift+Space"); Shell_NotifyIconW(NIM_ADD,&gNid); }
int APIENTRY wWinMain(HINSTANCE,HINSTANCE,LPWSTR cmd,int){ INITCOMMONCONTROLSEX icc{sizeof(icc),ICC_STANDARD_CLASSES|ICC_WIN95_CLASSES}; InitCommonControlsEx(&icc); SettingsManager settings; gSettings=&settings; settings.Load(); CorrectionEngine engine(settings); HWND hidden=CreateHidden(); if(!hidden){ MessageBoxW(nullptr,L"Unable to create korect background window.",L"korect",MB_OK|MB_ICONERROR); return 1;} AddTray(hidden); std::wstring err; if(!gHotkeys.Register(hidden,settings.Settings().openHotkey,err)) MessageBoxW(nullptr,err.c_str(),L"korect hotkey conflict",MB_OK|MB_ICONWARNING); OverlayWindow overlay(settings,engine,gOverlay); if(!overlay.Create()){ MessageBoxW(nullptr,L"Unable to create korect overlay window. RichEdit may be unavailable.",L"korect",MB_OK|MB_ICONERROR); return 2;} gOverlay.SetOverlay(&overlay); std::wstring arg=cmd?cmd:L""; if(arg.find(L"--minimized")==std::wstring::npos && !settings.Settings().startMinimized) overlay.Show(); MSG msg; while(GetMessageW(&msg,nullptr,0,0)>0){ TranslateMessage(&msg); DispatchMessageW(&msg);} gHotkeys.Unregister(); return 0; }
