#include "CorrectionEngine.h"
CorrectionEngine::CorrectionEngine(SettingsManager& s):settings_(s){ LoadDictionary(); ReloadPersonalDictionary(); }
void CorrectionEngine::ReloadPersonalDictionary(){ personal_.clear(); for(auto&w:settings_.Settings().personalDictionary) personal_.insert(Lower(w)); }
void CorrectionEngine::LoadDictionary(){
 const wchar_t* base=L"a about above after again against all almost also am an and another any are around as at be because been before being below between both but by can cannot could did do does doing down during each few for from further had has have having he her here hers herself him himself his how i if in into is it its itself just me more most my myself no nor not now of off on once only or other our ours ourselves out over own same she should so some such than that the their theirs them themselves then there these they this those through to too under until up very was we were what when where which while who whom why will with you your yours yourself yourselves went store yesterday bought milk sentence paragraph quick correct overlay window copy clear settings options language english hebrew russian punctuation grammar spelling error errors correction suggestion suggestions ignore dictionary text word words application game windowed fullscreen exclusive local offline privacy online service user enabled start minimized hotkey control shift space focus close escape dark light system accent font size opacity compact normal large performance cache debounce background cpu memory transparent topmost borderless restore previous foreground add remove import export reset current category advanced about personal dictionary enable disable automatic detection default numbers caps urls usernames technical terms obvious mistakes replace approval";
 std::wistringstream ss(base); std::wstring w; while(ss>>w) words_.insert(w);
 std::wstring extra=ReadAllText(AppDir()+L"\\dictionary.txt"); std::wistringstream es(extra); while(es>>w) words_.insert(Lower(w)); }
static bool isUrlLike(const std::wstring&w){ return StartsWith(Lower(w),L"http")||w.find(L".")!=std::wstring::npos; }
bool CorrectionEngine::IgnoredWord(const std::wstring& word){ auto&s=settings_.Settings(); if(word.empty()) return true; bool allcaps=true, anyalpha=false, anydigit=false; for(wchar_t c:word){ if(iswalpha(c)){anyalpha=true; if(iswlower(c)) allcaps=false;} if(iswdigit(c)) anydigit=true; } if(s.ignoreAllCaps&&allcaps&&anyalpha&&word.size()>1) return true; if(s.ignoreNumbers&&anydigit) return true; if(s.ignoreUrls&&isUrlLike(word)) return true; if(s.ignoreUsernames&&word[0]==L'@') return true; if(s.ignoreTechTerms&&(word.find(L'_')!=std::wstring::npos||word.find(L"::")!=std::wstring::npos)) return true; return false; }
int CorrectionEngine::Distance(const std::wstring&a,const std::wstring&b){ std::vector<int> prev(b.size()+1),cur(b.size()+1); for(size_t j=0;j<=b.size();++j)prev[j]=(int)j; for(size_t i=1;i<=a.size();++i){cur[0]=(int)i; for(size_t j=1;j<=b.size();++j){int cost=a[i-1]==b[j-1]?0:1; cur[j]=std::min({prev[j]+1,cur[j-1]+1,prev[j-1]+cost});} prev.swap(cur);} return prev.back(); }
std::vector<std::wstring> CorrectionEngine::Suggest(const std::wstring& word,int max){ std::vector<std::pair<int,std::wstring>> ranked; auto lw=Lower(word); for(auto& w:words_){ if(abs((int)w.size()-(int)lw.size())>3) continue; int d=Distance(lw,w); if(d<=3) ranked.push_back({d,w}); } std::sort(ranked.begin(),ranked.end()); std::vector<std::wstring> out; for(auto&p:ranked){ out.push_back(p.second); if((int)out.size()>=max) break; } return out; }
static bool LocalLanguageToolPortOpen(){ static bool wsa=false; if(!wsa){ WSADATA d{}; wsa=WSAStartup(MAKEWORD(2,2),&d)==0; if(!wsa) return false; } SOCKET s=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP); if(s==INVALID_SOCKET) return false; u_long nonblock=1; ioctlsocket(s,FIONBIO,&nonblock); sockaddr_in addr{}; addr.sin_family=AF_INET; addr.sin_port=htons(8081); inet_pton(AF_INET,"127.0.0.1",&addr.sin_addr); int r=connect(s,(sockaddr*)&addr,sizeof(addr)); if(r==SOCKET_ERROR&&WSAGetLastError()!=WSAEWOULDBLOCK){ closesocket(s); return false; } fd_set wfds; FD_ZERO(&wfds); FD_SET(s,&wfds); timeval tv{}; tv.tv_sec=0; tv.tv_usec=50000; r=select(0,nullptr,&wfds,nullptr,&tv); bool ok=false; if(r>0&&FD_ISSET(s,&wfds)){ int err=0; int len=sizeof(err); getsockopt(s,SOL_SOCKET,SO_ERROR,(char*)&err,&len); ok=err==0; } closesocket(s); return ok; }
bool CorrectionEngine::TryLanguageTool(const std::wstring& text,std::vector<CorrectionIssue>& out){
 auto&s=settings_.Settings(); if(s.offlineOnly && !s.allowOnline){ /* local LanguageTool only */ }
 auto now=std::chrono::steady_clock::now(); if(now<nextLanguageToolProbe_) return false;
 if(!LocalLanguageToolPortOpen()){ ltAvailable_=false; nextLanguageToolProbe_=now+std::chrono::seconds(30); return false; }
 HINTERNET ses=WinHttpOpen(L"korect/0.1",WINHTTP_ACCESS_TYPE_NO_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0); if(!ses) return false;
  WinHttpSetTimeouts(ses,25,25,25,75);
 HINTERNET con=WinHttpConnect(ses,L"127.0.0.1",8081,0); if(!con){WinHttpCloseHandle(ses); return false;}
 HINTERNET req=WinHttpOpenRequest(con,L"POST",L"/v2/check",nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,0); if(!req){WinHttpCloseHandle(con);WinHttpCloseHandle(ses);return false;}
 std::string body="language="+Narrow(s.autoLanguage?L"auto":s.defaultLanguage)+"&text="; std::string nt=Narrow(text.substr(0,(size_t)std::min((int)text.size(),s.maxTextLength))); for(unsigned char c:nt){ if(isalnum(c)||c==' '||c=='-'||c=='.'||c==',') body.push_back(c==' '?'+' : c); else { char buf[4]; sprintf(buf,"%%%02X",c); body+=buf; } }
 std::wstring hdr=L"Content-Type: application/x-www-form-urlencoded\r\n"; BOOL ok=WinHttpSendRequest(req,hdr.c_str(),(DWORD)-1,(LPVOID)body.data(),(DWORD)body.size(),(DWORD)body.size(),0)&&WinHttpReceiveResponse(req,nullptr); std::string resp; if(ok){ DWORD sz=0; while(WinHttpQueryDataAvailable(req,&sz)&&sz){ std::string buf(sz,'\0'); DWORD rd=0; WinHttpReadData(req,buf.data(),sz,&rd); buf.resize(rd); resp+=buf; }} WinHttpCloseHandle(req);WinHttpCloseHandle(con);WinHttpCloseHandle(ses); if(!ok||resp.empty()){ ltAvailable_=false; nextLanguageToolProbe_=std::chrono::steady_clock::now()+std::chrono::seconds(30); return false; } ltAvailable_=true;
 std::wstring wr=Widen(resp); std::wregex matchRe(L"\\\"offset\\\"\\s*:\\s*(\\d+).*?\\\"length\\\"\\s*:\\s*(\\d+).*?\\\"message\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"(.*?)\\\"replacements\\\"\\s*:\\s*\\[(.*?)\\]",std::regex::icase); auto b=std::wsregex_iterator(wr.begin(),wr.end(),matchRe), e=std::wsregex_iterator(); for(;b!=e;++b){ CorrectionIssue ci; ci.start=_wtol((*b)[1].str().c_str()); ci.length=_wtol((*b)[2].str().c_str()); ci.message=(*b)[3]; ci.type=IssueType::Grammar; std::wstring reps=(*b)[5]; std::wregex val(L"\\\"value\\\"\\s*:\\s*\\\"([^\\\"]*)\\\""); auto rb=std::wsregex_iterator(reps.begin(),reps.end(),val); for(;rb!=e;++rb) ci.suggestions.push_back((*rb)[1]); out.push_back(ci);} return !out.empty(); }
std::vector<CorrectionIssue> CorrectionEngine::Check(const std::wstring& text){ auto&s=settings_.Settings(); std::wstring trimmed=text.substr(0,(size_t)std::min((int)text.size(),s.maxTextLength)); if(s.cache){ std::lock_guard<std::mutex>l(cacheMutex_); auto it=cache_.find(trimmed); if(it!=cache_.end()) return it->second; }
 std::vector<CorrectionIssue> out; if(!s.allowOnline){ std::vector<CorrectionIssue> lt; TryLanguageTool(trimmed,lt); out.insert(out.end(),lt.begin(),lt.end()); }
 if(s.spelling){ std::wregex wr(L"[A-Za-z][A-Za-z'_-]*"); auto b=std::wsregex_iterator(trimmed.begin(),trimmed.end(),wr), e=std::wsregex_iterator(); for(;b!=e;++b){ std::wstring w=(*b).str(); auto lw=Lower(w); if(IgnoredWord(w)||words_.count(lw)||personal_.count(lw)) continue; CorrectionIssue ci; ci.start=(long)(*b).position(); ci.length=(long)w.size(); ci.type=IssueType::Spelling; ci.original=w; ci.message=L"Possible spelling error"; ci.suggestions=Suggest(w,s.suggestionCount); out.push_back(ci);} }
 if(s.grammar){ std::wregex rep(L"\\b([A-Za-z]+)\\s+\\1\\b",std::regex::icase); auto b=std::wsregex_iterator(trimmed.begin(),trimmed.end(),rep), e=std::wsregex_iterator(); for(;b!=e;++b){ CorrectionIssue ci; ci.start=(long)(*b).position(0); ci.length=(long)(*b).length(0); ci.type=IssueType::Grammar; ci.message=L"Repeated word"; ci.suggestions.push_back((*b)[1].str()); out.push_back(ci);} std::wregex lonei(L"\\bi\\b"); for(auto it=std::wsregex_iterator(trimmed.begin(),trimmed.end(),lonei);it!=e;++it){ CorrectionIssue ci; ci.start=(long)(*it).position(); ci.length=1; ci.type=IssueType::Grammar; ci.message=L"The pronoun I is usually capitalized"; ci.suggestions.push_back(L"I"); out.push_back(ci);} }
 if(s.punctuation){ std::wregex ds(L" {2,}"); auto b=std::wsregex_iterator(trimmed.begin(),trimmed.end(),ds), e=std::wsregex_iterator(); for(;b!=e;++b){ CorrectionIssue ci; ci.start=(long)(*b).position(); ci.length=(long)(*b).length(); ci.type=IssueType::Punctuation; ci.message=L"Multiple spaces"; ci.suggestions.push_back(L" "); out.push_back(ci);} std::wregex sp(L"\\s+([,.!?;:])"); for(auto it=std::wsregex_iterator(trimmed.begin(),trimmed.end(),sp);it!=e;++it){ CorrectionIssue ci; ci.start=(long)(*it).position(); ci.length=(long)(*it).length(); ci.type=IssueType::Punctuation; ci.message=L"Remove space before punctuation"; ci.suggestions.push_back((*it)[1]); out.push_back(ci);} }
 std::sort(out.begin(),out.end(),[](auto&a,auto&b){return a.start<b.start;}); if(s.cache){ std::lock_guard<std::mutex>l(cacheMutex_); if(cache_.size()>128) cache_.clear(); cache_[trimmed]=out; } return out; }
