#include "SettingsManager.h"
static std::wstring esc(const std::wstring& s){ std::wstring o; for(wchar_t c:s){ if(c==L'\\'||c==L'\"') {o+=L'\\';o+=c;} else if(c==L'\n') o+=L"\\n"; else o+=c;} return o; }
static bool getBool(const std::wstring&t,const wchar_t* k,bool d){ std::wregex r(L"\\\""+std::wstring(k)+L"\\\"\\s*:\\s*(true|false)",std::regex::icase); std::wsmatch m; return std::regex_search(t,m,r)? Lower(m[1])==L"true":d; }
static int getInt(const std::wstring&t,const wchar_t* k,int d){ std::wregex r(L"\\\""+std::wstring(k)+L"\\\"\\s*:\\s*(-?\\d+)"); std::wsmatch m; return std::regex_search(t,m,r)? _wtoi(m[1].str().c_str()):d; }
static std::wstring getStr(const std::wstring&t,const wchar_t* k,const std::wstring& d){ std::wregex r(L"\\\""+std::wstring(k)+L"\\\"\\s*:\\s*\\\"([^\\\"]*)\\\""); std::wsmatch m; return std::regex_search(t,m,r)?m[1].str():d; }
SettingsManager::SettingsManager(){ configPath_=UserConfigDir()+L"\\settings.json"; }
bool SettingsManager::Load(){ std::wstring t=ReadAllText(configPath_); if(t.empty()){ Save(); return true; } try{ Parse(t); return true; }catch(...){ MessageBoxW(nullptr,L"Settings were unreadable; korect loaded defaults.",L"korect settings",MB_OK|MB_ICONWARNING); return false; } }
bool SettingsManager::Save(){ WriteAllText(configPath_,Serialize()); HKEY key; if(RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,nullptr,0,KEY_SET_VALUE,nullptr,&key,nullptr)==ERROR_SUCCESS){ if(settings_.startWithWindows){ wchar_t exe[MAX_PATH]; GetModuleFileNameW(nullptr,exe,MAX_PATH); std::wstring cmd=L"\""+std::wstring(exe)+L"\" --minimized"; RegSetValueExW(key,L"korect",0,REG_SZ,(const BYTE*)cmd.c_str(),(DWORD)((cmd.size()+1)*sizeof(wchar_t))); } else RegDeleteValueW(key,L"korect"); RegCloseKey(key);} return true; }
void SettingsManager::ResetAll(){ settings_=AppSettings(); Save(); }
bool SettingsManager::ImportFrom(const std::wstring& p){ auto t=ReadAllText(p); if(t.empty()) return false; Parse(t); return Save(); }
bool SettingsManager::ExportTo(const std::wstring& p){ WriteAllText(p,Serialize()); return true; }
void SettingsManager::AddDictionaryWord(const std::wstring& w){ auto lw=Lower(Trim(w)); if(lw.empty()) return; if(std::find(settings_.personalDictionary.begin(),settings_.personalDictionary.end(),lw)==settings_.personalDictionary.end()) settings_.personalDictionary.push_back(lw); Save(); }
void SettingsManager::RemoveDictionaryWord(const std::wstring& w){ auto lw=Lower(Trim(w)); settings_.personalDictionary.erase(std::remove(settings_.personalDictionary.begin(),settings_.personalDictionary.end(),lw),settings_.personalDictionary.end()); Save(); }
void SettingsManager::Parse(const std::wstring&t){
    settings_.openHotkey.modifiers=(UINT)getInt(t,L"openHotkeyModifiers",settings_.openHotkey.modifiers); settings_.openHotkey.vk=(UINT)getInt(t,L"openHotkeyVk",settings_.openHotkey.vk);
    settings_.startWithWindows=getBool(t,L"startWithWindows",settings_.startWithWindows); settings_.startMinimized=getBool(t,L"startMinimized",settings_.startMinimized); settings_.alwaysOnTop=getBool(t,L"alwaysOnTop",settings_.alwaysOnTop); settings_.closeWithEscape=getBool(t,L"closeWithEscape",settings_.closeWithEscape); settings_.closeOnOutside=getBool(t,L"closeOnOutside",settings_.closeOnOutside);
    settings_.autoCloseAfterCopy=getBool(t,L"autoCloseAfterCopy",settings_.autoCloseAfterCopy); settings_.openAnimation=getBool(t,L"openAnimation",settings_.openAnimation); settings_.closeAnimation=getBool(t,L"closeAnimation",settings_.closeAnimation);
    settings_.overlayWidth=getInt(t,L"overlayWidth",settings_.overlayWidth); settings_.overlayHeight=getInt(t,L"overlayHeight",settings_.overlayHeight); settings_.overlayX=getInt(t,L"overlayX",settings_.overlayX); settings_.overlayY=getInt(t,L"overlayY",settings_.overlayY); settings_.overlayPosition=getStr(t,L"overlayPosition",settings_.overlayPosition);
    settings_.theme=getStr(t,L"theme",settings_.theme); settings_.accent=getStr(t,L"accent",settings_.accent); settings_.textColor=getStr(t,L"textColor",settings_.textColor); settings_.fontFamily=getStr(t,L"fontFamily",settings_.fontFamily); settings_.interfaceSize=getStr(t,L"interfaceSize",settings_.interfaceSize);
    settings_.opacity=getInt(t,L"opacity",settings_.opacity); settings_.fontSize=getInt(t,L"fontSize",settings_.fontSize); settings_.uiScale=getInt(t,L"uiScale",settings_.uiScale); settings_.borderRadius=getInt(t,L"borderRadius",settings_.borderRadius); settings_.showButtons=getBool(t,L"showButtons",settings_.showButtons); settings_.showTitleBar=getBool(t,L"showTitleBar",settings_.showTitleBar);
    settings_.spelling=getBool(t,L"spelling",settings_.spelling); settings_.grammar=getBool(t,L"grammar",settings_.grammar); settings_.punctuation=getBool(t,L"punctuation",settings_.punctuation); settings_.autoLanguage=getBool(t,L"autoLanguage",settings_.autoLanguage); settings_.autoBest=getBool(t,L"autoBest",settings_.autoBest); settings_.autoCorrect=getBool(t,L"autoCorrect",settings_.autoCorrect);
    settings_.ignoreAllCaps=getBool(t,L"ignoreAllCaps",settings_.ignoreAllCaps); settings_.ignoreNumbers=getBool(t,L"ignoreNumbers",settings_.ignoreNumbers); settings_.ignoreUrls=getBool(t,L"ignoreUrls",settings_.ignoreUrls); settings_.ignoreUsernames=getBool(t,L"ignoreUsernames",settings_.ignoreUsernames); settings_.ignoreTechTerms=getBool(t,L"ignoreTechTerms",settings_.ignoreTechTerms); settings_.defaultLanguage=getStr(t,L"defaultLanguage",settings_.defaultLanguage);
    settings_.correctionDelayMs=getInt(t,L"correctionDelayMs",settings_.correctionDelayMs); settings_.suggestionCount=getInt(t,L"suggestionCount",settings_.suggestionCount); settings_.maxTextLength=getInt(t,L"maxTextLength",settings_.maxTextLength);
    settings_.offlineOnly=getBool(t,L"offlineOnly",settings_.offlineOnly); settings_.allowOnline=getBool(t,L"allowOnline",settings_.allowOnline); settings_.cache=getBool(t,L"cache",settings_.cache); settings_.engineInBackground=getBool(t,L"engineInBackground",settings_.engineInBackground); settings_.startEngineWithWindows=getBool(t,L"startEngineWithWindows",settings_.startEngineWithWindows); settings_.keepEngineLoaded=getBool(t,L"keepEngineLoaded",settings_.keepEngineLoaded); settings_.reduceCpu=getBool(t,L"reduceCpu",settings_.reduceCpu);
    settings_.personalDictionary.clear(); std::wregex arr(L"\\\"personalDictionary\\\"\\s*:\\s*\\[([^\\]]*)\\]"); std::wsmatch m; if(std::regex_search(t,m,arr)){ std::wregex item(L"\\\"([^\\\"]+)\\\""); auto b=std::wsregex_iterator(m[1].first,m[1].second,item), e=std::wsregex_iterator(); for(;b!=e;++b) settings_.personalDictionary.push_back(Lower((*b)[1])); }
}
std::wstring SettingsManager::Serialize() const{ const auto&s=settings_; std::wstringstream o; o<<L"{\n";
#define B(k,v) o<<L"  \""<<k<<L"\": "<<((v)?L"true":L"false")<<L",\n"
#define I(k,v) o<<L"  \""<<k<<L"\": "<<(v)<<L",\n"
#define S(k,v) o<<L"  \""<<k<<L"\": \""<<esc(v)<<L"\",\n"
I(L"openHotkeyModifiers",s.openHotkey.modifiers); I(L"openHotkeyVk",s.openHotkey.vk); B(L"startWithWindows",s.startWithWindows); B(L"startMinimized",s.startMinimized); B(L"alwaysOnTop",s.alwaysOnTop); B(L"closeWithEscape",s.closeWithEscape); B(L"closeOnOutside",s.closeOnOutside); B(L"autoCloseAfterCopy",s.autoCloseAfterCopy); B(L"openAnimation",s.openAnimation); B(L"closeAnimation",s.closeAnimation); I(L"overlayWidth",s.overlayWidth); I(L"overlayHeight",s.overlayHeight); I(L"overlayX",s.overlayX); I(L"overlayY",s.overlayY); S(L"overlayPosition",s.overlayPosition); S(L"theme",s.theme); S(L"accent",s.accent); S(L"textColor",s.textColor); S(L"fontFamily",s.fontFamily); I(L"opacity",s.opacity); I(L"fontSize",s.fontSize); I(L"uiScale",s.uiScale); I(L"borderRadius",s.borderRadius); S(L"interfaceSize",s.interfaceSize); B(L"showButtons",s.showButtons); B(L"showTitleBar",s.showTitleBar); B(L"spelling",s.spelling); B(L"grammar",s.grammar); B(L"punctuation",s.punctuation); B(L"autoLanguage",s.autoLanguage); B(L"autoBest",s.autoBest); B(L"autoCorrect",s.autoCorrect); B(L"ignoreAllCaps",s.ignoreAllCaps); B(L"ignoreNumbers",s.ignoreNumbers); B(L"ignoreUrls",s.ignoreUrls); B(L"ignoreUsernames",s.ignoreUsernames); B(L"ignoreTechTerms",s.ignoreTechTerms); S(L"defaultLanguage",s.defaultLanguage); I(L"correctionDelayMs",s.correctionDelayMs); I(L"suggestionCount",s.suggestionCount); I(L"maxTextLength",s.maxTextLength); B(L"offlineOnly",s.offlineOnly); B(L"allowOnline",s.allowOnline); B(L"cache",s.cache); B(L"engineInBackground",s.engineInBackground); B(L"startEngineWithWindows",s.startEngineWithWindows); B(L"keepEngineLoaded",s.keepEngineLoaded); B(L"reduceCpu",s.reduceCpu); o<<L"  \"personalDictionary\": ["; for(size_t i=0;i<s.personalDictionary.size();++i){ if(i)o<<L", "; o<<L"\""<<esc(s.personalDictionary[i])<<L"\"";} o<<L"]\n}\n"; return o.str(); }
