#include "OptionsWindow.h"
OptionsWindow::OptionsWindow(SettingsManager& s):sm_(s){ cats_={L"Appearance",L"Overlay",L"Hotkeys",L"Correction",L"Languages",L"Dictionary",L"Privacy",L"Performance",L"Advanced",L"About"}; }
bool OptionsWindow::Create(HWND owner){ WNDCLASSW wc{}; wc.lpfnWndProc=WndProc; wc.hInstance=GetModuleHandleW(nullptr); wc.lpszClassName=L"KorectOptionsWindow"; wc.hCursor=LoadCursor(nullptr,IDC_ARROW); wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1); RegisterClassW(&wc); hwnd_=CreateWindowExW(WS_EX_TOOLWINDOW,L"KorectOptionsWindow",L"korect Options",WS_OVERLAPPEDWINDOW|WS_CLIPCHILDREN,CW_USEDEFAULT,CW_USEDEFAULT,760,560,owner,nullptr,wc.hInstance,this); return hwnd_!=nullptr; }
void OptionsWindow::Show(){ if(!hwnd_) return; ShowWindow(hwnd_,SW_SHOWNORMAL); SetForegroundWindow(hwnd_); }
LRESULT CALLBACK OptionsWindow::WndProc(HWND h,UINT m,WPARAM w,LPARAM l){ OptionsWindow* p=(OptionsWindow*)GetWindowLongPtrW(h,GWLP_USERDATA); if(m==WM_NCCREATE){ p=(OptionsWindow*)((CREATESTRUCTW*)l)->lpCreateParams; SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)p); p->hwnd_=h;} return p?p->Proc(m,w,l):DefWindowProcW(h,m,w,l); }
LRESULT CALLBACK OptionsWindow::PanelProc(HWND h,UINT m,WPARAM w,LPARAM l){ OptionsWindow* p=(OptionsWindow*)GetWindowLongPtrW(h,GWLP_USERDATA); if(p&&(m==WM_COMMAND||m==WM_NOTIFY)){ return SendMessageW(p->hwnd_,m,w,l); } return DefWindowProcW(h,m,w,l); }
HWND OptionsWindow::AddCheck(const std::wstring& text,bool& val,int y){ HWND c=CreateWindowW(L"BUTTON",text.c_str(),WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,20,y,300,24,panel_,(HMENU)(INT_PTR)(1000+y),GetModuleHandleW(nullptr),nullptr); Button_SetCheck(c,val?BST_CHECKED:BST_UNCHECKED); SetWindowLongPtrW(c,GWLP_USERDATA,(LONG_PTR)&val); return c; }
HWND OptionsWindow::AddEdit(const std::wstring& text,std::wstring& val,int y){ CreateWindowW(L"STATIC",text.c_str(),WS_CHILD|WS_VISIBLE,20,y,180,22,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); HWND e=CreateWindowW(L"EDIT",val.c_str(),WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,220,y,230,24,panel_,(HMENU)(INT_PTR)(2000+y),GetModuleHandleW(nullptr),nullptr); SetWindowLongPtrW(e,GWLP_USERDATA,(LONG_PTR)&val); return e; }
HWND OptionsWindow::AddInt(const std::wstring& text,int& val,int y){ CreateWindowW(L"STATIC",text.c_str(),WS_CHILD|WS_VISIBLE,20,y,180,22,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); wchar_t b[32]; wsprintfW(b,L"%d",val); HWND e=CreateWindowW(L"EDIT",b,WS_CHILD|WS_VISIBLE|WS_BORDER|ES_NUMBER,220,y,120,24,panel_,(HMENU)(INT_PTR)(3000+y),GetModuleHandleW(nullptr),nullptr); SetWindowLongPtrW(e,GWLP_USERDATA,(LONG_PTR)&val); return e; }
void OptionsWindow::BuildCategory(){ if(panel_) DestroyWindow(panel_); panel_=CreateWindowW(L"STATIC",L"",WS_CHILD|WS_VISIBLE,180,10,560,500,hwnd_,nullptr,GetModuleHandleW(nullptr),nullptr); SetWindowLongPtrW(panel_,GWLP_USERDATA,(LONG_PTR)this); SetWindowLongPtrW(panel_,GWLP_WNDPROC,(LONG_PTR)PanelProc); auto&s=sm_.Settings(); int y=10; std::wstring title=L"QuickCorrect Options - "+cats_[category_]; CreateWindowW(L"STATIC",title.c_str(),WS_CHILD|WS_VISIBLE,20,y,480,24,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); y+=34;
 switch(category_){
 case 0: AddEdit(L"Theme (Light/Dark/System)",s.theme,y); y+=32; AddEdit(L"Accent color (#RRGGBB)",s.accent,y); y+=32; AddEdit(L"Text color",s.textColor,y); y+=32; AddEdit(L"Font",s.fontFamily,y); y+=32; AddInt(L"Font size",s.fontSize,y); y+=32; AddInt(L"UI scale",s.uiScale,y); y+=32; AddInt(L"Border radius",s.borderRadius,y); y+=32; AddEdit(L"Compact/Normal/Large",s.interfaceSize,y); y+=32; AddCheck(L"Show buttons",s.showButtons,y); y+=28; AddCheck(L"Show title bar",s.showTitleBar,y); break;
 case 1: AddInt(L"Overlay width",s.overlayWidth,y); y+=32; AddInt(L"Overlay height",s.overlayHeight,y); y+=32; AddEdit(L"Position (Center/Top/Bottom/Custom)",s.overlayPosition,y); y+=32; AddInt(L"Custom X",s.overlayX,y); y+=32; AddInt(L"Custom Y",s.overlayY,y); y+=32; AddInt(L"Overlay opacity 50-255",s.opacity,y); y+=32; AddCheck(L"Always on top",s.alwaysOnTop,y); y+=28; AddCheck(L"Automatically close after copying",s.autoCloseAfterCopy,y); y+=28; AddCheck(L"Close with Escape",s.closeWithEscape,y); y+=28; AddCheck(L"Close when clicking outside",s.closeOnOutside,y); y+=28; AddCheck(L"Open animation",s.openAnimation,y); y+=28; AddCheck(L"Close animation",s.closeAnimation,y); break;
 case 2: AddInt(L"Open overlay modifiers",(int&)s.openHotkey.modifiers,y); y+=32; AddInt(L"Open overlay VK",(int&)s.openHotkey.vk,y); y+=32; CreateWindowW(L"STATIC",L"Default is Ctrl+Shift+Space. If RegisterHotKey fails, another app owns it; change VK/modifiers and restart.",WS_CHILD|WS_VISIBLE,20,y,500,46,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); break;
 case 3: AddCheck(L"Enable spelling correction",s.spelling,y); y+=28; AddCheck(L"Enable grammar correction",s.grammar,y); y+=28; AddCheck(L"Enable punctuation correction",s.punctuation,y); y+=28; AddCheck(L"Automatic language detection",s.autoLanguage,y); y+=28; AddEdit(L"Default language",s.defaultLanguage,y); y+=32; AddInt(L"Correction delay ms",s.correctionDelayMs,y); y+=32; AddInt(L"Number of suggestions",s.suggestionCount,y); y+=32; AddCheck(L"Automatically select best suggestion",s.autoBest,y); y+=28; AddCheck(L"Automatically correct obvious mistakes",s.autoCorrect,y); y+=28; CreateWindowW(L"STATIC",L"Known dictionary words are never spelling-autocorrected; korect only flags unknown words.",WS_CHILD|WS_VISIBLE,20,y,500,34,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); y+=38; AddCheck(L"Ignore ALL CAPS",s.ignoreAllCaps,y); y+=28; AddCheck(L"Ignore URLs",s.ignoreUrls,y); y+=28; AddCheck(L"Ignore usernames",s.ignoreUsernames,y); y+=28; AddCheck(L"Ignore numbers",s.ignoreNumbers,y); y+=28; AddCheck(L"Ignore technical terms",s.ignoreTechTerms,y); break;
 case 4: CreateWindowW(L"STATIC",L"Installed/local languages: Automatic, English. Hebrew/Russian/other languages are available when a local LanguageTool server with those languages is running on 127.0.0.1:8081.",WS_CHILD|WS_VISIBLE,20,y,500,80,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); break;
 case 5: { CreateWindowW(L"STATIC",L"Personal Dictionary (one word per line)",WS_CHILD|WS_VISIBLE,20,y,300,22,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); y+=24; std::wstring words; for(auto&w:s.personalDictionary) words+=w+L"\r\n"; HWND e=CreateWindowW(L"EDIT",words.c_str(),WS_CHILD|WS_VISIBLE|WS_BORDER|ES_MULTILINE|WS_VSCROLL,20,y,420,240,panel_,(HMENU)2600,GetModuleHandleW(nullptr),nullptr); SetWindowLongPtrW(e,GWLP_USERDATA,9999); y+=250; CreateWindowW(L"BUTTON",L"Import...",WS_CHILD|WS_VISIBLE,20,y,90,26,panel_,(HMENU)501,GetModuleHandleW(nullptr),nullptr); CreateWindowW(L"BUTTON",L"Export...",WS_CHILD|WS_VISIBLE,120,y,90,26,panel_,(HMENU)502,GetModuleHandleW(nullptr),nullptr); CreateWindowW(L"BUTTON",L"Clear",WS_CHILD|WS_VISIBLE,220,y,90,26,panel_,(HMENU)503,GetModuleHandleW(nullptr),nullptr); break; }
 case 6: AddCheck(L"Offline/local correction only",s.offlineOnly,y); y+=28; AddCheck(L"Allow online correction services",s.allowOnline,y); y+=32; CreateWindowW(L"STATIC",L"Online is disabled by default. korect never sends text externally unless explicitly enabled. Current implementation only contacts local LanguageTool at 127.0.0.1 unless you enable online support in future builds.",WS_CHILD|WS_VISIBLE,20,y,500,80,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); break;
 case 7: AddCheck(L"Enable correction caching",s.cache,y); y+=28; AddInt(L"Correction debounce delay",s.correctionDelayMs,y); y+=32; AddInt(L"Maximum text length",s.maxTextLength,y); y+=32; AddCheck(L"Run correction engine in background",s.engineInBackground,y); y+=28; AddCheck(L"Start correction engine when Windows starts",s.startEngineWithWindows,y); y+=28; AddCheck(L"Keep correction engine loaded",s.keepEngineLoaded,y); y+=28; AddCheck(L"Reduce background CPU usage",s.reduceCpu,y); break;
 case 8: AddCheck(L"Start with Windows",s.startWithWindows,y); y+=28; AddCheck(L"Start minimized",s.startMinimized,y); y+=28; CreateWindowW(L"BUTTON",L"Reset all settings",WS_CHILD|WS_VISIBLE,20,y,150,28,panel_,(HMENU)601,GetModuleHandleW(nullptr),nullptr); y+=36; CreateWindowW(L"BUTTON",L"Import settings",WS_CHILD|WS_VISIBLE,20,y,150,28,panel_,(HMENU)602,GetModuleHandleW(nullptr),nullptr); CreateWindowW(L"BUTTON",L"Export settings",WS_CHILD|WS_VISIBLE,180,y,150,28,panel_,(HMENU)603,GetModuleHandleW(nullptr),nullptr); break;
 case 9: CreateWindowW(L"STATIC",L"korect / QuickCorrect\r\nLightweight native Win32 overlay.\r\nLocal rule-based spelling/grammar is built in. Local LanguageTool is used automatically when available at 127.0.0.1:8081.\r\nExclusive-fullscreen games can block normal topmost overlays; use borderless/windowed mode.",WS_CHILD|WS_VISIBLE,20,y,500,140,panel_,nullptr,GetModuleHandleW(nullptr),nullptr); break; }
 CreateWindowW(L"BUTTON",L"Apply",WS_CHILD|WS_VISIBLE,20,455,90,28,panel_,(HMENU)605,GetModuleHandleW(nullptr),nullptr); CreateWindowW(L"BUTTON",L"Reset current category",WS_CHILD|WS_VISIBLE,120,455,160,28,panel_,(HMENU)604,GetModuleHandleW(nullptr),nullptr); }
void OptionsWindow::ApplyCurrentControls(){ if(!panel_) return; for(HWND c=GetWindow(panel_,GW_CHILD); c; c=GetWindow(c,GW_HWNDNEXT)){ LONG_PTR ptr=GetWindowLongPtrW(c,GWLP_USERDATA); if(!ptr) continue; int id=GetDlgCtrlID(c); wchar_t cls[32]{}; GetClassNameW(c,cls,32); if(_wcsicmp(cls,L"Button")==0){ *(bool*)ptr=Button_GetCheck(c)==BST_CHECKED; } else if(_wcsicmp(cls,L"Edit")==0){ int len=GetWindowTextLengthW(c); std::wstring text(len,0); GetWindowTextW(c,text.data(),len+1); if(ptr==9999){ sm_.Settings().personalDictionary.clear(); std::wistringstream ss(text); std::wstring word; while(ss>>word) sm_.Settings().personalDictionary.push_back(Lower(Trim(word))); } else if(id>=3000){ *(int*)ptr=_wtoi(text.c_str()); } else { *(std::wstring*)ptr=text; } } } }
void OptionsWindow::SaveAndRefresh(){ sm_.Save(); }
bool OptionsWindow::ChooseFile(bool save, std::wstring& out, const wchar_t* filter){ wchar_t file[MAX_PATH]{}; OPENFILENAMEW ofn{}; ofn.lStructSize=sizeof(ofn); ofn.hwndOwner=hwnd_; ofn.lpstrFilter=filter; ofn.lpstrFile=file; ofn.nMaxFile=MAX_PATH; ofn.Flags=OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST); BOOL ok=save?GetSaveFileNameW(&ofn):GetOpenFileNameW(&ofn); if(ok) out=file; return ok; }
void OptionsWindow::ResetCategory(){ AppSettings d; auto&s=sm_.Settings(); switch(category_){ case 0: s.theme=d.theme; s.accent=d.accent; s.textColor=d.textColor; s.fontFamily=d.fontFamily; s.fontSize=d.fontSize; s.uiScale=d.uiScale; s.borderRadius=d.borderRadius; s.interfaceSize=d.interfaceSize; s.showButtons=d.showButtons; s.showTitleBar=d.showTitleBar; break; case 1: s.overlayWidth=d.overlayWidth; s.overlayHeight=d.overlayHeight; s.overlayPosition=d.overlayPosition; s.overlayX=d.overlayX; s.overlayY=d.overlayY; s.opacity=d.opacity; s.alwaysOnTop=d.alwaysOnTop; s.autoCloseAfterCopy=d.autoCloseAfterCopy; s.closeWithEscape=d.closeWithEscape; s.closeOnOutside=d.closeOnOutside; s.openAnimation=d.openAnimation; s.closeAnimation=d.closeAnimation; break; case 2: s.openHotkey=d.openHotkey; break; case 3: s.spelling=d.spelling; s.grammar=d.grammar; s.punctuation=d.punctuation; s.autoLanguage=d.autoLanguage; s.defaultLanguage=d.defaultLanguage; s.correctionDelayMs=d.correctionDelayMs; s.suggestionCount=d.suggestionCount; s.autoBest=d.autoBest; s.autoCorrect=d.autoCorrect; s.ignoreAllCaps=d.ignoreAllCaps; s.ignoreUrls=d.ignoreUrls; s.ignoreUsernames=d.ignoreUsernames; s.ignoreNumbers=d.ignoreNumbers; s.ignoreTechTerms=d.ignoreTechTerms; break; case 5: s.personalDictionary.clear(); break; case 6: s.offlineOnly=d.offlineOnly; s.allowOnline=d.allowOnline; break; case 7: s.cache=d.cache; s.correctionDelayMs=d.correctionDelayMs; s.maxTextLength=d.maxTextLength; s.engineInBackground=d.engineInBackground; s.startEngineWithWindows=d.startEngineWithWindows; s.keepEngineLoaded=d.keepEngineLoaded; s.reduceCpu=d.reduceCpu; break; case 8: s.startWithWindows=d.startWithWindows; s.startMinimized=d.startMinimized; break; default: break;} sm_.Save(); BuildCategory(); }
LRESULT OptionsWindow::Proc(UINT m,WPARAM w,LPARAM l){
    switch(m){
    case WM_CREATE:
        list_=CreateWindowW(L"LISTBOX",L"",WS_CHILD|WS_VISIBLE|LBS_NOTIFY|WS_BORDER,10,10,155,500,hwnd_,(HMENU)10,GetModuleHandleW(nullptr),nullptr);
        for(auto&c:cats_) SendMessageW(list_,LB_ADDSTRING,0,(LPARAM)c.c_str());
        SendMessageW(list_,LB_SETCURSEL,0,0); BuildCategory(); return 0;
    case WM_COMMAND:{
        int id=LOWORD(w), code=HIWORD(w);
        if((HWND)l==list_&&code==LBN_SELCHANGE){ ApplyCurrentControls(); sm_.Save(); category_=(int)SendMessageW(list_,LB_GETCURSEL,0,0); BuildCategory(); }
        else if(id==501){ std::wstring f; if(ChooseFile(false,f,L"Text files\0*.txt\0All files\0*.*\0")){ std::wistringstream ss(ReadAllText(f)); std::wstring word; while(ss>>word) sm_.AddDictionaryWord(word); BuildCategory(); } }
        else if(id==502){ std::wstring f; if(ChooseFile(true,f,L"Text files\0*.txt\0All files\0*.*\0")){ std::wstring out; for(auto&w:sm_.Settings().personalDictionary) out+=w+L"\r\n"; WriteAllText(f,out); } }
        else if(id==503){ sm_.Settings().personalDictionary.clear(); sm_.Save(); BuildCategory(); }
        else if(id==601){ sm_.ResetAll(); BuildCategory(); }
        else if(id==602){ std::wstring f; if(ChooseFile(false,f,L"JSON settings\0*.json\0All files\0*.*\0")){ if(!sm_.ImportFrom(f)) MessageBoxW(hwnd_,L"Could not import settings.",L"korect",MB_OK|MB_ICONWARNING); BuildCategory(); } }
        else if(id==603){ std::wstring f; if(ChooseFile(true,f,L"JSON settings\0*.json\0All files\0*.*\0")) sm_.ExportTo(f); }
        else if(id==604){ ResetCategory(); }
        else if(id==605){ ApplyCurrentControls(); sm_.Save(); MessageBoxW(hwnd_,L"Options applied and saved. Some changes, like the global hotkey, may require restarting korect.",L"korect",MB_OK|MB_ICONINFORMATION); }
        else if(code==BN_CLICKED){ HWND c=(HWND)l; auto ptr=GetWindowLongPtrW(c,GWLP_USERDATA); if(ptr){ *(bool*)ptr = Button_GetCheck(c)==BST_CHECKED; sm_.Save(); }}
        else if(code==EN_CHANGE){ HWND e=(HWND)l; auto ptr=GetWindowLongPtrW(e,GWLP_USERDATA); if(ptr==9999){ int len=GetWindowTextLengthW(e); std::wstring text(len,0); GetWindowTextW(e,text.data(),len+1); sm_.Settings().personalDictionary.clear(); std::wistringstream ss(text); std::wstring word; while(ss>>word) sm_.Settings().personalDictionary.push_back(Lower(Trim(word))); sm_.Save(); } else if(ptr){ wchar_t buf[512]; GetWindowTextW(e,buf,512); if(id>=3000) *(int*)ptr=_wtoi(buf); else *(std::wstring*)ptr=buf; sm_.Save(); }}
        return 0;}
    case WM_CLOSE: ShowWindow(hwnd_,SW_HIDE); return 0;
    }
    return DefWindowProcW(hwnd_,m,w,l);
}
