#include "OverlayWindow.h"
#include "../System/OverlayManager.h"
static HMODULE LoadRich(){ static HMODULE h=LoadLibraryW(L"Msftedit.dll"); if(!h) h=LoadLibraryW(L"Riched20.dll"); return h; }
OverlayWindow::OverlayWindow(SettingsManager&s,CorrectionEngine&e,OverlayManager&m):sm_(s),engine_(e),manager_(m),options_(s){}
bool OverlayWindow::Create(){ LoadRich(); WNDCLASSW wc{}; wc.lpfnWndProc=WndProc; wc.hInstance=GetModuleHandleW(nullptr); wc.lpszClassName=L"KorectOverlayWindow"; wc.hCursor=LoadCursor(nullptr,IDC_ARROW); wc.hbrBackground=(HBRUSH)GetStockObject(NULL_BRUSH); RegisterClassW(&wc); DWORD ex=WS_EX_TOOLWINDOW|WS_EX_LAYERED; if(sm_.Settings().alwaysOnTop) ex|=WS_EX_TOPMOST; hwnd_=CreateWindowExW(ex,L"KorectOverlayWindow",L"korect",WS_POPUP|WS_CLIPCHILDREN,0,0,sm_.Settings().overlayWidth,sm_.Settings().overlayHeight,nullptr,nullptr,wc.hInstance,this); if(!hwnd_) return false; SetLayeredWindowAttributes(hwnd_,0,(BYTE)sm_.Settings().opacity,LWA_ALPHA); edit_=CreateWindowExW(0,MSFTEDIT_CLASS,L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL|ES_WANTRETURN,18,48,520,200,hwnd_,(HMENU)100,GetModuleHandleW(nullptr),nullptr); if(!edit_) edit_=CreateWindowExW(0,RICHEDIT_CLASS,L"",WS_CHILD|WS_VISIBLE|WS_TABSTOP|ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL|ES_WANTRETURN,18,48,520,200,hwnd_,(HMENU)100,GetModuleHandleW(nullptr),nullptr);
 SendMessageW(edit_,EM_SETBKGNDCOLOR,0,RGB(17,24,39)); SendMessageW(edit_,EM_SETEVENTMASK,0,ENM_CHANGE|ENM_MOUSEEVENTS|ENM_KEYEVENTS); CHARFORMAT2W cf{}; cf.cbSize=sizeof(cf); cf.dwMask=CFM_COLOR|CFM_FACE|CFM_SIZE; cf.crTextColor=ParseColor(sm_.Settings().textColor,RGB(229,231,235)); cf.yHeight=sm_.Settings().fontSize*20; wcsncpy(cf.szFaceName,sm_.Settings().fontFamily.c_str(),LF_FACESIZE-1); SendMessageW(edit_,EM_SETCHARFORMAT,SCF_ALL,(LPARAM)&cf);
 copy_=CreateWindowW(L"BUTTON",L"Copy",WS_CHILD|WS_VISIBLE,0,0,70,28,hwnd_,(HMENU)201,GetModuleHandleW(nullptr),nullptr); copyClose_=CreateWindowW(L"BUTTON",L"Copy && Close",WS_CHILD|WS_VISIBLE,0,0,110,28,hwnd_,(HMENU)202,GetModuleHandleW(nullptr),nullptr); clear_=CreateWindowW(L"BUTTON",L"Clear",WS_CHILD|WS_VISIBLE,0,0,70,28,hwnd_,(HMENU)203,GetModuleHandleW(nullptr),nullptr); settings_=CreateWindowW(L"BUTTON",L"Options",WS_CHILD|WS_VISIBLE,0,0,80,28,hwnd_,(HMENU)204,GetModuleHandleW(nullptr),nullptr); options_.Create(hwnd_); Layout(); return true; }
void OverlayWindow::Layout(){ auto&s=sm_.Settings(); RECT wa; SystemParametersInfoW(SPI_GETWORKAREA,0,&wa,0); int w=s.overlayWidth,h=s.overlayHeight,x=(wa.right-wa.left-w)/2,y=(wa.bottom-wa.top-h)/2; if(s.overlayPosition==L"Top") y=wa.top+40; else if(s.overlayPosition==L"Bottom") y=wa.bottom-h-40; else if(s.overlayPosition==L"Custom"&&s.overlayX>=0&&s.overlayY>=0){x=s.overlayX;y=s.overlayY;} SetWindowPos(hwnd_,s.alwaysOnTop?HWND_TOPMOST:HWND_NOTOPMOST,x,y,w,h,SWP_NOACTIVATE); int m=18,title=s.showTitleBar?42:16,btn=42; MoveWindow(edit_,m,title,w-2*m,h-title-btn-m,TRUE); int by=h-34,bx=m; if(s.showButtons){ ShowWindow(copy_,SW_SHOW); ShowWindow(copyClose_,SW_SHOW); ShowWindow(clear_,SW_SHOW); ShowWindow(settings_,SW_SHOW); MoveWindow(copy_,bx,by,75,27,TRUE); MoveWindow(copyClose_,bx+84,by,112,27,TRUE); MoveWindow(clear_,bx+205,by,75,27,TRUE); MoveWindow(settings_,w-100,by,82,27,TRUE);} else {ShowWindow(copy_,SW_HIDE);ShowWindow(copyClose_,SW_HIDE);ShowWindow(clear_,SW_HIDE);ShowWindow(settings_,SW_HIDE);} }
void OverlayWindow::Show(){ Layout(); SetLayeredWindowAttributes(hwnd_,0,(BYTE)sm_.Settings().opacity,LWA_ALPHA); ShowWindow(hwnd_,SW_SHOWNORMAL); SetWindowPos(hwnd_,HWND_TOPMOST,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE); visible_=true; SetForegroundWindow(hwnd_); SetFocus(edit_); ScheduleCheck(); }
void OverlayWindow::Hide(){ ShowWindow(hwnd_,SW_HIDE); visible_=false; }
std::wstring OverlayWindow::Text()const{ int len=GetWindowTextLengthW(edit_); std::wstring t(len,0); GetWindowTextW(edit_,t.data(),len+1); return t; }
void OverlayWindow::Copy(bool close){ auto t=Text(); if(OpenClipboard(hwnd_)){ EmptyClipboard(); HGLOBAL h=GlobalAlloc(GMEM_MOVEABLE,(t.size()+1)*sizeof(wchar_t)); if(h){ memcpy(GlobalLock(h),t.c_str(),(t.size()+1)*sizeof(wchar_t)); GlobalUnlock(h); SetClipboardData(CF_UNICODETEXT,h);} CloseClipboard(); } if(close||sm_.Settings().autoCloseAfterCopy) manager_.Hide(true); }
void OverlayWindow::Clear(){ SetWindowTextW(edit_,L""); issues_.clear(); ApplyIssues(issues_); }
void OverlayWindow::ScheduleCheck(){ KillTimer(hwnd_,1); SetTimer(hwnd_,1,(UINT)std::max(100,sm_.Settings().correctionDelayMs),nullptr); }
void OverlayWindow::StartCheck(){ auto text=Text(); future_=std::async(std::launch::async,[this,text](){ return engine_.Check(text); }); std::thread([this](){ auto r=future_.get(); auto heap=new std::vector<CorrectionIssue>(std::move(r)); PostMessageW(hwnd_,WM_CORRECTION_DONE,0,(LPARAM)heap); }).detach(); }
void OverlayWindow::ApplyIssues(const std::vector<CorrectionIssue>& is){ CHARRANGE all{0,-1}; SendMessageW(edit_,EM_EXSETSEL,0,(LPARAM)&all); CHARFORMAT2W clear{}; clear.cbSize=sizeof(clear); clear.dwMask=CFM_UNDERLINE|CFM_UNDERLINETYPE; clear.dwEffects=0; clear.bUnderlineType=CFU_UNDERLINENONE; SendMessageW(edit_,EM_SETCHARFORMAT,SCF_SELECTION,(LPARAM)&clear); for(auto&ci:is){ CHARRANGE cr{ci.start,ci.start+ci.length}; SendMessageW(edit_,EM_EXSETSEL,0,(LPARAM)&cr); CHARFORMAT2W cf{}; cf.cbSize=sizeof(cf); cf.dwMask=CFM_UNDERLINE|CFM_UNDERLINETYPE; cf.dwEffects=CFE_UNDERLINE; cf.bUnderlineType= ci.type==IssueType::Spelling?CFU_UNDERLINEWAVE:(ci.type==IssueType::Grammar?CFU_UNDERLINEDOTTED:CFU_UNDERLINE); SendMessageW(edit_,EM_SETCHARFORMAT,SCF_SELECTION,(LPARAM)&cf);} CHARRANGE end{-1,-1}; SendMessageW(edit_,EM_EXSETSEL,0,(LPARAM)&end); }
int OverlayWindow::IssueAtPoint(POINT p){ POINT ep=p; ScreenToClient(edit_,&ep); long idx=(long)SendMessageW(edit_,EM_CHARFROMPOS,0,(LPARAM)&ep); for(size_t i=0;i<issues_.size();++i) if(idx>=issues_[i].start&&idx<=issues_[i].start+issues_[i].length) return (int)i; return -1; }
void OverlayWindow::ReplaceIssue(int idx,const std::wstring& sug){ if(idx<0||idx>=(int)issues_.size())return; auto ci=issues_[idx]; CHARRANGE cr{ci.start,ci.start+ci.length}; SendMessageW(edit_,EM_EXSETSEL,0,(LPARAM)&cr); SendMessageW(edit_,EM_REPLACESEL,TRUE,(LPARAM)sug.c_str()); ScheduleCheck(); }
void OverlayWindow::ShowContextMenu(POINT p){ contextIssue_=IssueAtPoint(p); if(context_) DestroyMenu(context_); context_=CreatePopupMenu(); if(contextIssue_>=0){ auto&ci=issues_[contextIssue_]; AppendMenuW(context_,MF_DISABLED,0,ci.original.empty()?L"Issue":ci.original.c_str()); AppendMenuW(context_,MF_SEPARATOR,0,nullptr); int id=300; for(auto&sug:ci.suggestions) AppendMenuW(context_,MF_STRING,id++,sug.c_str()); if(ci.suggestions.empty()) AppendMenuW(context_,MF_DISABLED,0,L"No suggestions"); AppendMenuW(context_,MF_SEPARATOR,0,nullptr); AppendMenuW(context_,MF_STRING,401,L"Ignore"); AppendMenuW(context_,MF_STRING,402,L"Ignore all"); AppendMenuW(context_,MF_STRING,403,L"Add to dictionary"); } else { AppendMenuW(context_,MF_STRING,201,L"Copy"); AppendMenuW(context_,MF_STRING,203,L"Clear"); } TrackPopupMenu(context_,TPM_RIGHTBUTTON,p.x,p.y,0,hwnd_,nullptr); }
void OverlayWindow::PaintBackground(HDC hdc){ RECT r; GetClientRect(hwnd_,&r); HBRUSH bg=CreateSolidBrush(sm_.Settings().theme==L"Light"?RGB(245,247,250):RGB(11,18,32)); FillRect(hdc,&r,bg); DeleteObject(bg); HPEN pen=CreatePen(PS_SOLID,1,ParseColor(sm_.Settings().accent,RGB(103,232,249))); SelectObject(hdc,pen); SelectObject(hdc,GetStockObject(NULL_BRUSH)); RoundRect(hdc,0,0,r.right,r.bottom,sm_.Settings().borderRadius,sm_.Settings().borderRadius); DeleteObject(pen); SetBkMode(hdc,TRANSPARENT); SetTextColor(hdc,ParseColor(sm_.Settings().textColor,RGB(229,231,235))); HFONT font=CreateFontW(20,0,0,0,FW_SEMIBOLD,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,CLEARTYPE_QUALITY,DEFAULT_PITCH,L"Segoe UI"); SelectObject(hdc,font); if(sm_.Settings().showTitleBar) TextOutW(hdc,18,14,L"QuickCorrect",12); DeleteObject(font); }
LRESULT CALLBACK OverlayWindow::WndProc(HWND h,UINT m,WPARAM w,LPARAM l){ OverlayWindow*p=(OverlayWindow*)GetWindowLongPtrW(h,GWLP_USERDATA); if(m==WM_NCCREATE){ p=(OverlayWindow*)((CREATESTRUCTW*)l)->lpCreateParams; SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)p); p->hwnd_=h;} return p?p->Proc(m,w,l):DefWindowProcW(h,m,w,l); }
LRESULT OverlayWindow::Proc(UINT m,WPARAM w,LPARAM l){ switch(m){ case WM_PAINT:{ PAINTSTRUCT ps; HDC h=BeginPaint(hwnd_,&ps); PaintBackground(h); EndPaint(hwnd_,&ps); return 0;} case WM_SIZE: Layout(); return 0; case WM_TIMER: KillTimer(hwnd_,1); StartCheck(); return 0; case WM_CORRECTION_DONE:{ auto v=(std::vector<CorrectionIssue>*)l; issues_=*v; delete v; ApplyIssues(issues_); return 0;} case WM_COMMAND:{ int id=LOWORD(w); if(id==201)Copy(false); else if(id==202)Copy(true); else if(id==203)Clear(); else if(id==204)options_.Show(); else if(id>=300&&id<400&&contextIssue_>=0){ auto& sug=issues_[contextIssue_].suggestions[id-300]; ReplaceIssue(contextIssue_,sug);} else if(id==401&&contextIssue_>=0){issues_.erase(issues_.begin()+contextIssue_); ApplyIssues(issues_);} else if(id==402&&contextIssue_>=0){ auto word=Lower(issues_[contextIssue_].original); issues_.erase(std::remove_if(issues_.begin(),issues_.end(),[&](auto&i){return Lower(i.original)==word;}),issues_.end()); ApplyIssues(issues_);} else if(id==403&&contextIssue_>=0){ sm_.AddDictionaryWord(issues_[contextIssue_].original); engine_.ReloadPersonalDictionary(); ScheduleCheck(); } return 0;} case WM_NOTIFY:{ NMHDR* n=(NMHDR*)l; if(n->hwndFrom==edit_&&n->code==EN_MSGFILTER){ MSGFILTER* mf=(MSGFILTER*)l; if(mf->msg==WM_RBUTTONUP){ POINT p{GET_X_LPARAM(mf->lParam),GET_Y_LPARAM(mf->lParam)}; ClientToScreen(edit_,&p); ShowContextMenu(p); return 1; }} return 0;} case WM_CTLCOLOREDIT:{ SetTextColor((HDC)w,ParseColor(sm_.Settings().textColor,RGB(229,231,235))); SetBkColor((HDC)w,RGB(17,24,39)); static HBRUSH br=CreateSolidBrush(RGB(17,24,39)); return (LRESULT)br;} case WM_KEYDOWN: if(w==VK_ESCAPE&&sm_.Settings().closeWithEscape){ manager_.Hide(true); return 0;} if((GetKeyState(VK_CONTROL)&0x8000)&&w=='C'){ Copy(false); return 0;} if((GetKeyState(VK_CONTROL)&0x8000)&&w=='L'){ Clear(); return 0;} return 0; case WM_ACTIVATE: if(LOWORD(w)==WA_INACTIVE&&sm_.Settings().closeOnOutside) manager_.Hide(false); return 0; case WM_CLOSE: manager_.Hide(true); return 0;} return DefWindowProcW(hwnd_,m,w,l); }
